// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6WwSqyylyeYcGzB5-VoeSq2SuY2pnmGI',
    appId: '1:830161432722:web:9f6ab95337e545e9adb64b',
    messagingSenderId: '830161432722',
    projectId: 'american-center-82eff',
    authDomain: 'american-center-82eff.firebaseapp.com',
    storageBucket: 'american-center-82eff.firebasestorage.app',
    measurementId: 'G-27DME5DZ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUEuNidmC2U4bk_P_Y20yBw6rt729KeY',
    appId: '1:830161432722:android:c7b78e80f254839aadb64b',
    messagingSenderId: '830161432722',
    projectId: 'american-center-82eff',
    storageBucket: 'american-center-82eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPwW33Ak-gDiAKGqb-tdPMqzRmMU1x6g',
    appId: '1:830161432722:ios:8a31b253b4771722adb64b',
    messagingSenderId: '830161432722',
    projectId: 'american-center-82eff',
    storageBucket: 'american-center-82eff.firebasestorage.app',
    iosBundleId: 'com.karimelabasy.quizdent.quizdent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPwW33Ak-gDiAKGqb-tdPMqzRmMU1x6g',
    appId: '1:830161432722:ios:8a31b253b4771722adb64b',
    messagingSenderId: '830161432722',
    projectId: 'american-center-82eff',
    storageBucket: 'american-center-82eff.firebasestorage.app',
    iosBundleId: 'com.karimelabasy.quizdent.quizdent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6WwSqyylyeYcGzB5-VoeSq2SuY2pnmGI',
    appId: '1:830161432722:web:42f33f804e92d82fadb64b',
    messagingSenderId: '830161432722',
    projectId: 'american-center-82eff',
    authDomain: 'american-center-82eff.firebaseapp.com',
    storageBucket: 'american-center-82eff.firebasestorage.app',
    measurementId: 'G-W0VNCL8S9X',
  );

}